language: c

sudo: required
dist: trusty

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libmsgpack3 libmsgpack-dev libuv0.10 libuv-dev
  - wget -O /tmp/libbframe_1.0.0-1_amd64.deb https://s3.amazonaws.com/tools.microbox.cloud/deb/libbframe_1.0.0-1_amd64.deb
  - wget -O /tmp/libmsgxchng_1.0.0-1_amd64.deb https://s3.amazonaws.com/tools.microbox.cloud/deb/libmsgxchng_1.0.0-1_amd64.deb
  - sudo dpkg -i /tmp/libbframe_1.0.0-1_amd64.deb
  - sudo dpkg -i /tmp/libmsgxchng_1.0.0-1_amd64.deb
  - mkdir m4
  - autoreconf -fvi

script: ./configure && make
